version: "3.2"

services:
  mariadb:
    image: mariadb:10.7
    container_name: mariadb
    hostname: mariadb
    volumes:
      - mysql-glpi:/var/lib/mysql
    env_file:
      - ./mariadb.env
    restart: always

  glpi:
    image: hansnewton/glpi
    build:
      context: .
      dockerfile: Dockerfile
    container_name : glpi
    hostname: glpi
    ports:
      - "80:80"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TIMEZONE=America/Sao_Paulo
      - VERSION_GLPI=10.0.5
    restart: always

volumes:
  mysql-glpi: